artifacts_root: artifacts

data_ingestion:
  root_dir: "artifacts/data_ingestion"
  source_URL: "data/samsumdata.zip"
  local_data_file: "artifacts/data_ingestion/file.zip"
  unzip_dir: "artifacts/data_ingestion"

data_validation:
  root_dir: "artifacts/data_validation"
  STATUS_FILE: "artifacts/data_validation/status_file.txt"
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  root_dir: "artifacts/data_transformation"
  data_path: "artifacts/data_ingestion/samsum_dataset"
  tokenizer_name: "google/pegasus-cnn_dailymail"
